CREATE TABLE `testuser` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255),
  `email` VARCHAR(255),
  `password` VARCHAR(255),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- SQL inserts for `user` table
-- Inserts 50 sample users. Adjust passwords/emails as needed.

INSERT INTO `user` (`name`, `email`, `password`) VALUES
('Alice Johnson','alice.johnson001@example.com','password001'),
('Bob Smith','bob.smith002@example.com','password002'),
('Carla Martinez','carla.martinez003@example.com','password003'),
('Daniel Lee','daniel.lee004@example.com','password004'),
('Elena Garcia','elena.garcia005@example.com','password005'),
('Frank Nguyen','frank.nguyen006@example.com','password006'),
('Grace Kim','grace.kim007@example.com','password007'),
('Henry Brown','henry.brown008@example.com','password008'),
('Ivy Wilson','ivy.wilson009@example.com','password009'),
('Jack Turner','jack.turner010@example.com','password010'),
('Kara Patel','kara.patel011@example.com','password011'),
('Liam O\'Connor','liam.oconnor012@example.com','password012'),
('Maya Singh','maya.singh013@example.com','password013'),
('Noah Davis','noah.davis014@example.com','password014'),
('Olivia Evans','olivia.evans015@example.com','password015'),
('Peter Rossi','peter.rossi016@example.com','password016'),
('Quinn Baker','quinn.baker017@example.com','password017'),
('Rosa Alvarez','rosa.alvarez018@example.com','password018'),
('Samir Khan','samir.khan019@example.com','password019'),
('Tara Wilson','tara.wilson020@example.com','password020'),
('Ulysses Reed','ulysses.reed021@example.com','password021'),
('Vera Cooper','vera.cooper022@example.com','password022'),
('Will Harris','will.harris023@example.com','password023'),
('Xena Flores','xena.flores024@example.com','password024'),
('Yusuf Ali','yusuf.ali025@example.com','password025'),
('Zoe Brooks','zoe.brooks026@example.com','password026'),
('Aaron Cole','aaron.cole027@example.com','password027'),
('Bianca Cruz','bianca.cruz028@example.com','password028'),
('Cody Young','cody.young029@example.com','password029'),
('Diana Moore','diana.moore030@example.com','password030'),
('Ethan Bell','ethan.bell031@example.com','password031'),
('Fiona Stone','fiona.stone032@example.com','password032'),
('Gavin Price','gavin.price033@example.com','password033'),
('Hannah Green','hannah.green034@example.com','password034'),
('Ian Walker','ian.walker035@example.com','password035'),
('Jade Reed','jade.reed036@example.com','password036'),
('Kyle Bennett','kyle.bennett037@example.com','password037'),
('Lola Grant','lola.grant038@example.com','password038'),
('Mason Knight','mason.knight039@example.com','password039'),
('Nina Fox','nina.fox040@example.com','password040'),
('Omar Price','omar.price041@example.com','password041'),
('Piper Shaw','piper.shaw042@example.com','password042'),
('Quentin Hale','quentin.hale043@example.com','password043'),
('Riley Stone','riley.stone044@example.com','password044'),
('Sofia Vega','sofia.vega045@example.com','password045'),
('Theo Marsh','theo.marsh046@example.com','password046'),
('Una Boyd','una.boyd047@example.com','password047'),
('Victor Lane','victor.lane048@example.com','password048'),
('Wendy Park','wendy.park049@example.com','password049'),
('Xavier Hunt','xavier.hunt050@example.com','password050');
